# Performing Gradient Descent on Logistic Regression

In [5]:
import numpy as np

def sigmoid(a_i):
    return 1 / (1 + np.exp(-a_i))

def gradient(w_i, X, Y):
    sum = 0
    for i in range(len(X)):
        x_i = X[i]
        y_i = Y[i]
        a_i = np.dot(w_i, x_i)
        p_i = sigmoid(a_i)
        sum += (y_i - p_i) * x_i

    return -sum

### Iteration 1

In [6]:
w_i = np.array([0.3, -0.2, 0.7])

X = np.array([[4.0, 4.0, 1.0],
                [6.0, 4.0, 1.0],
                [6.0, 5.0, 1.0],
                [6.0, 8.0, 1.0],
                [6.0, 10.0, 1.0],
                [8.0, 8.0, 1.0],
                [8.0, 10.0, 1.0]])

Y = np.array([1, 1, 1, 0, 0, 1, 0])
Y_inv = np.array([0, 0, 0, 1, 1, 0, 1])

step_size = 0.01

w_iplus1 = w_i - step_size * gradient(w_i, X, Y)
print(w_iplus1)

[ 0.20477175 -0.35426438  0.68685387]


### Iteration 2

In [7]:
w_iplus2 = w_iplus1 - step_size * gradient(w_iplus1, X, Y)
print(w_iplus2)

[ 0.27913091 -0.3089443   0.69951893]


### Iteration 3

In [9]:
w_iplus3 = w_iplus2 - step_size * gradient(w_iplus2, X, Y)
print(w_iplus3)

[ 0.27208574 -0.35574855  0.69978802]
